#include "nsISupports.idl"

[scriptable, uuid(f380ecd6-5e8d-4e11-8d85-d16a8e28e6d0)]
interface IMypgp : nsISupports
{
	/**
	*  Create Types 
	*
	*  LONG_KEY    - 2046 bits key.
	*  SHORT_KEY   - 1024 bits key.
	*/
	const unsigned long LONG_KEY = 0;
	const unsigned long SHORT_KEY = 1;

    /**
     * Creates an object with session key encrypted plus ciphertext
     */
    void secureMsg(in string plaintext, in long lenght, in string keyPath);

	/**
	 * Encrypt/Decrypt msgs from keysession
	 */
	string encrypt(in string plaintext, in string keysession);
	string decrypt(in string cyphertext, in string keysession);

	/**
	 * Generate Private/Public Key
	 */
	void keygen(in unsigned long type, in string path);

	/**
	 * Generate Session Key and return it
	 */
	string sessionKeygen(in long keySize, in long ivSize);
	

	long add(in long a, in long b);
};
	
